export type Lang = 'en' | 'zh';

export const t = {
  en: {
    title: "Endfield Robots Helper",
    subtitle: "Create, edit, and solve custom tiling puzzles",
    boardSetup: "Board Setup",
    clearFixed: "Clear Fixed Cells",
    width: "Width",
    height: "Height",
    targetSums: "Target Sums & Fixed Positions",
    instructions: "Click cells to toggle fixed positions. Enter target sums in the headers.",
    empty: "Empty",
    fixed0: "Fixed 0 (X)",
    fixed1: "Fixed 1 (O)",
    puzzlePieces: "Puzzle Pieces",
    addPiece: "Add Piece",
    pieceType: "Piece Type",
    qty: "Qty",
    duplicate: "Duplicate",
    remove: "Remove",
    solve: "Solve Puzzle",
    solving: "Solving...",
    findPlacements: "Find all valid placements",
    solutionsFound: "Solutions Found",
    timeTaken: "Time taken",
    noSolutions: "No solutions found.",
    noSolutionsDesc: "The current board configuration and puzzle pieces cannot be arranged to satisfy all constraints. Try adjusting the target sums, fixed positions, or puzzle shapes.",
    solution: "Solution",
    of: "of",
    prev: "Prev",
    next: "Next",
    ms: "ms",
    changeColor: "Change color"
  },
  zh: {
    title: "终末地笨笨机器人Helper",
    subtitle: "暴力求解自定义拼图",
    boardSetup: "目标图案设置",
    clearFixed: "清除固定单元格",
    width: "宽度",
    height: "高度",
    targetSums: "目标和与固定位置",
    instructions: "点击单元格切换固定位置。在表头输入目标和。",
    empty: "空",
    fixed0: "固定 0 (X)",
    fixed1: "固定 1 (O)",
    puzzlePieces: "拼图块",
    addPiece: "添加拼图块",
    pieceType: "拼图类型",
    qty: "数量",
    duplicate: "复制",
    remove: "移除",
    solve: "求解拼图",
    solving: "求解中...",
    findPlacements: "查找所有有效的放置方式",
    solutionsFound: "找到的解",
    timeTaken: "耗时",
    noSolutions: "未找到解。",
    noSolutionsDesc: "当前的棋盘配置和拼图块无法满足所有约束条件。请尝试调整目标和、固定位置或拼图形状。",
    solution: "解",
    of: "/",
    prev: "上一个",
    next: "下一个",
    ms: "毫秒",
    changeColor: "更改颜色"
  }
};
